spring.application.name=rcs-system
spring.datasource.url=jdbc:postgresql://localhost:8432/rcs_db
spring.datasource.username=rcs_user
spring.datasource.password=rcs_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

server.port=8088

# AccuPick TCP (RCS is TCP client per SDD)

rcs.accupick.host=127.0.0.1
rcs.accupick.port=12345
rcs.accupick.mock-enabled=false
rcs.accupick.server.enabled=false

rcs.wes.server.port=10010
rcs.wes.client.host=127.0.0.1
rcs.wes.client.port=10001
rcs.wes.client.timeout-ms=5000
rcs.wes.base-url=http://127.0.0.1:8081/api/v1
rcs.wes.token=
rcs.wes.callback-enabled=true
